// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/LabStateDTO.proto

package data;

public final class LabStateDTO {
  private LabStateDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LabStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.LabState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string code = 1;</code>
     * @return Whether the code field is set.
     */
    boolean hasCode();
    /**
     * <code>required string code = 1;</code>
     * @return The code.
     */
    java.lang.String getCode();
    /**
     * <code>required string code = 1;</code>
     * @return The bytes for code.
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>required string results = 2;</code>
     * @return Whether the results field is set.
     */
    boolean hasResults();
    /**
     * <code>required string results = 2;</code>
     * @return The results.
     */
    java.lang.String getResults();
    /**
     * <code>required string results = 2;</code>
     * @return The bytes for results.
     */
    com.google.protobuf.ByteString
        getResultsBytes();

    /**
     * <code>required string funnyJokes = 3;</code>
     * @return Whether the funnyJokes field is set.
     */
    boolean hasFunnyJokes();
    /**
     * <code>required string funnyJokes = 3;</code>
     * @return The funnyJokes.
     */
    java.lang.String getFunnyJokes();
    /**
     * <code>required string funnyJokes = 3;</code>
     * @return The bytes for funnyJokes.
     */
    com.google.protobuf.ByteString
        getFunnyJokesBytes();
  }
  /**
   * Protobuf type {@code protobuf.LabState}
   */
  public static final class LabState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.LabState)
      LabStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LabState.newBuilder() to construct.
    private LabState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LabState() {
      code_ = "";
      results_ = "";
      funnyJokes_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LabState();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LabState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              code_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              results_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              funnyJokes_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return data.LabStateDTO.internal_static_protobuf_LabState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return data.LabStateDTO.internal_static_protobuf_LabState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              data.LabStateDTO.LabState.class, data.LabStateDTO.LabState.Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object code_;
    /**
     * <code>required string code = 1;</code>
     * @return Whether the code field is set.
     */
    @java.lang.Override
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string code = 1;</code>
     * @return The bytes for code.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULTS_FIELD_NUMBER = 2;
    private volatile java.lang.Object results_;
    /**
     * <code>required string results = 2;</code>
     * @return Whether the results field is set.
     */
    @java.lang.Override
    public boolean hasResults() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string results = 2;</code>
     * @return The results.
     */
    @java.lang.Override
    public java.lang.String getResults() {
      java.lang.Object ref = results_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          results_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string results = 2;</code>
     * @return The bytes for results.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultsBytes() {
      java.lang.Object ref = results_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        results_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNNYJOKES_FIELD_NUMBER = 3;
    private volatile java.lang.Object funnyJokes_;
    /**
     * <code>required string funnyJokes = 3;</code>
     * @return Whether the funnyJokes field is set.
     */
    @java.lang.Override
    public boolean hasFunnyJokes() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string funnyJokes = 3;</code>
     * @return The funnyJokes.
     */
    @java.lang.Override
    public java.lang.String getFunnyJokes() {
      java.lang.Object ref = funnyJokes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          funnyJokes_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string funnyJokes = 3;</code>
     * @return The bytes for funnyJokes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFunnyJokesBytes() {
      java.lang.Object ref = funnyJokes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        funnyJokes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResults()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFunnyJokes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, results_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, funnyJokes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, results_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, funnyJokes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof data.LabStateDTO.LabState)) {
        return super.equals(obj);
      }
      data.LabStateDTO.LabState other = (data.LabStateDTO.LabState) obj;

      if (hasCode() != other.hasCode()) return false;
      if (hasCode()) {
        if (!getCode()
            .equals(other.getCode())) return false;
      }
      if (hasResults() != other.hasResults()) return false;
      if (hasResults()) {
        if (!getResults()
            .equals(other.getResults())) return false;
      }
      if (hasFunnyJokes() != other.hasFunnyJokes()) return false;
      if (hasFunnyJokes()) {
        if (!getFunnyJokes()
            .equals(other.getFunnyJokes())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode().hashCode();
      }
      if (hasResults()) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResults().hashCode();
      }
      if (hasFunnyJokes()) {
        hash = (37 * hash) + FUNNYJOKES_FIELD_NUMBER;
        hash = (53 * hash) + getFunnyJokes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static data.LabStateDTO.LabState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.LabStateDTO.LabState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.LabStateDTO.LabState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.LabStateDTO.LabState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.LabStateDTO.LabState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.LabStateDTO.LabState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.LabStateDTO.LabState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.LabStateDTO.LabState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.LabStateDTO.LabState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static data.LabStateDTO.LabState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.LabStateDTO.LabState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.LabStateDTO.LabState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(data.LabStateDTO.LabState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.LabState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.LabState)
        data.LabStateDTO.LabStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.LabStateDTO.internal_static_protobuf_LabState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.LabStateDTO.internal_static_protobuf_LabState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.LabStateDTO.LabState.class, data.LabStateDTO.LabState.Builder.class);
      }

      // Construct using data.LabStateDTO.LabState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        results_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        funnyJokes_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return data.LabStateDTO.internal_static_protobuf_LabState_descriptor;
      }

      @java.lang.Override
      public data.LabStateDTO.LabState getDefaultInstanceForType() {
        return data.LabStateDTO.LabState.getDefaultInstance();
      }

      @java.lang.Override
      public data.LabStateDTO.LabState build() {
        data.LabStateDTO.LabState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public data.LabStateDTO.LabState buildPartial() {
        data.LabStateDTO.LabState result = new data.LabStateDTO.LabState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.results_ = results_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.funnyJokes_ = funnyJokes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof data.LabStateDTO.LabState) {
          return mergeFrom((data.LabStateDTO.LabState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(data.LabStateDTO.LabState other) {
        if (other == data.LabStateDTO.LabState.getDefaultInstance()) return this;
        if (other.hasCode()) {
          bitField0_ |= 0x00000001;
          code_ = other.code_;
          onChanged();
        }
        if (other.hasResults()) {
          bitField0_ |= 0x00000002;
          results_ = other.results_;
          onChanged();
        }
        if (other.hasFunnyJokes()) {
          bitField0_ |= 0x00000004;
          funnyJokes_ = other.funnyJokes_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCode()) {
          return false;
        }
        if (!hasResults()) {
          return false;
        }
        if (!hasFunnyJokes()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        data.LabStateDTO.LabState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (data.LabStateDTO.LabState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object code_ = "";
      /**
       * <code>required string code = 1;</code>
       * @return Whether the code field is set.
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string code = 1;</code>
       * @return The code.
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string code = 1;</code>
       * @return The bytes for code.
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string code = 1;</code>
       * @param value The bytes for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object results_ = "";
      /**
       * <code>required string results = 2;</code>
       * @return Whether the results field is set.
       */
      public boolean hasResults() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string results = 2;</code>
       * @return The results.
       */
      public java.lang.String getResults() {
        java.lang.Object ref = results_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            results_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string results = 2;</code>
       * @return The bytes for results.
       */
      public com.google.protobuf.ByteString
          getResultsBytes() {
        java.lang.Object ref = results_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          results_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string results = 2;</code>
       * @param value The results to set.
       * @return This builder for chaining.
       */
      public Builder setResults(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        results_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string results = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResults() {
        bitField0_ = (bitField0_ & ~0x00000002);
        results_ = getDefaultInstance().getResults();
        onChanged();
        return this;
      }
      /**
       * <code>required string results = 2;</code>
       * @param value The bytes for results to set.
       * @return This builder for chaining.
       */
      public Builder setResultsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        results_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object funnyJokes_ = "";
      /**
       * <code>required string funnyJokes = 3;</code>
       * @return Whether the funnyJokes field is set.
       */
      public boolean hasFunnyJokes() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string funnyJokes = 3;</code>
       * @return The funnyJokes.
       */
      public java.lang.String getFunnyJokes() {
        java.lang.Object ref = funnyJokes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            funnyJokes_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string funnyJokes = 3;</code>
       * @return The bytes for funnyJokes.
       */
      public com.google.protobuf.ByteString
          getFunnyJokesBytes() {
        java.lang.Object ref = funnyJokes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          funnyJokes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string funnyJokes = 3;</code>
       * @param value The funnyJokes to set.
       * @return This builder for chaining.
       */
      public Builder setFunnyJokes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        funnyJokes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string funnyJokes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFunnyJokes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        funnyJokes_ = getDefaultInstance().getFunnyJokes();
        onChanged();
        return this;
      }
      /**
       * <code>required string funnyJokes = 3;</code>
       * @param value The bytes for funnyJokes to set.
       * @return This builder for chaining.
       */
      public Builder setFunnyJokesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        funnyJokes_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.LabState)
    }

    // @@protoc_insertion_point(class_scope:protobuf.LabState)
    private static final data.LabStateDTO.LabState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new data.LabStateDTO.LabState();
    }

    public static data.LabStateDTO.LabState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LabState>
        PARSER = new com.google.protobuf.AbstractParser<LabState>() {
      @java.lang.Override
      public LabState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LabState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LabState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LabState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public data.LabStateDTO.LabState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_LabState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_LabState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/main/resources/LabStateDTO.proto\022\010" +
      "protobuf\"=\n\010LabState\022\014\n\004code\030\001 \002(\t\022\017\n\007re" +
      "sults\030\002 \002(\t\022\022\n\nfunnyJokes\030\003 \002(\tB\023\n\004dataB" +
      "\013LabStateDTO"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_LabState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_LabState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_LabState_descriptor,
        new java.lang.String[] { "Code", "Results", "FunnyJokes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
